crud/urls.py
from django.urls import path

from . import views

app_name = 'crud'
urlpatterns = [
    path('', views.index, name='index'),

    path('<str:item>/add/', views.add, name='add'),
    path('<str:item>/<uuid:id>/', views.edit, name='edit'),
    path('<str:item>/<uuid:id>/delete', views.delete, name='delete'),
 
    path('products/', views.products, name='products'),
    path('locations/', views.locations, name='locations'),
    path('inventory/', views.inventory, name='inventory'),
]

shopifycrud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls'))
]

crud/models.py
import uuid
from decimal import Decimal

from django.db import models
from django.core.validators import MinValueValidator
from django.db.models.deletion import SET_NULL

class Location(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200, unique=True, help_text='Name of the location.')

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name = 'location'

class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200, unique=True, help_text='Name of the product')
    price = models.DecimalField(max_digits=17, decimal_places=2, help_text='Current price of the product. Cannot be less than $0.01.', validators=[MinValueValidator(Decimal('0.01'))])

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name = 'product'

class Inventory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    stock = models.PositiveIntegerField(default=0, help_text='The amount of product available in this inventory item.')

    location = models.ForeignKey(Location, blank=True, null=True, on_delete=SET_NULL, help_text='The location where this inventory is stored.')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, help_text='The product contained in the inventory item.')

    def __str__(self):
        return self.product.name + ' Inventory'

    class Meta:
        ordering = ['product']
        verbose_name = 'inventory item'

crud/forms.py
from django.forms import ModelForm

from .models import Location, Product, Inventory

class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = ['name']

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price']

class InventoryForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ['stock', 'location', 'product']

crud/views.py
import uuid

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Inventory, Location, Product
from .forms import LocationForm, ProductForm, InventoryForm

def index(request):
    context = {
        'products': Product.objects.all(),
        'locations': Location.objects.all(),
        'inventory': Inventory.objects.all(),
    }

    return render(request, 'crud/index.html', context)

def add(request, item: str):
    item = item.lower()

    if item == 'products':
        form = ProductForm
    elif item == 'locations':
        form = LocationForm
    elif item == 'inventory':
        form = InventoryForm

    if request.method == 'POST':
        form = form(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('crud:{}'.format(item)))
    else:
        form = form()
    return render(request, 'crud/add_form.html', {'form': form, 'type': item})

def edit(request, item: str, id: uuid.uuid4):
    item = item.lower()

    if item == 'products':
        form = ProductForm
        edit_item = Product.objects.get(id=id)
    elif item == 'locations':
        form = LocationForm
        edit_item = Location.objects.get(id=id)
    elif item == 'inventory':
        form = InventoryForm
        edit_item = Inventory.objects.get(id=id)

    if request.method == 'POST':
        form = form(request.POST, instance=edit_item)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('crud:{}'.format(item)))
    else:
        form = form(instance=edit_item)

        context = {'edit_item': edit_item, 'form': form, 'type': item}
        
    return render(request, 'crud/edit_form.html', context)

def delete(request, item: str, id: uuid.uuid4):
    item = item.lower()

    if item == 'products':
        form = ProductForm
        del_item = Product.objects.get(id=id)
    elif item == 'locations':
        form = LocationForm
        del_item = Location.objects.get(id=id)
    elif item == 'inventory':
        form = InventoryForm
        del_item = Inventory.objects.get(id=id)

    if request.method == 'POST':
        del_item.delete()
        return HttpResponseRedirect(reverse('crud:{}'.format(item)))
    
    context = {'del_item': del_item}

    return render(request, 'crud/delete.html', context)


def products(request):
    context = {'products': Product.objects.all()}

    return render(request, 'crud/products.html', context)

def locations(request):

    context = {'locations': Location.objects.all()}
    
    return render(request, 'crud/locations.html', context)

def inventory(request):

    context = {'inventory': Inventory.objects.all()}
    
    return render(request, 'crud/inventory.html', context)

crud/templates/crud/add_form.html
{% extends 'crud/index.html' %}

{% block content %}
    <div>New {{ type }}</div>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

crud/templates/crud/delete.html
{% extends 'crud/index.html' %}

{% block content %}
    {% if del_item %}
        <form action="" method="POST">
            {% csrf_token %}
            <h4>Are you sure you want to delete {{ del_item }}? This action cannot be undone.</h4>
            <input type="submit" value="Delete">
        </form>        
    {% endif %}
{% endblock content %}

crud/templates/crud/edit_form.html
{% extends 'crud/index.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Save">
    </form>
    <a href="{% url 'crud:delete' type edit_item.id %}">Delete {{ type }}</a>
{% endblock content %}

crud/templates/crud/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block stylesheet %}
        <link rel="stylesheet" href="{% static 'crud/index.css' %}">
    {% endblock %}
    <title>CRUD inventory app</title>
</head>
<body>
    {% block header %}
        <header id="header">
            <a href="/">Home</a>
            <a href="/products/">Products</a>
            <a href="/inventory/">Inventory</a>
            <a href="/locations/">Locations</a>
        </header>
    {% endblock header %}
<div class="wrapper">
    {% block content %}
            <section id='all-products'>
                <h3>All products</h3>
                    <table>
                        <thead>
                            <tr>
                                <th></th>
                                <th>Name</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a href="/products/{{ product.id }}/">{{ product.name }}</a></td>
                                    <td>${{ product.price }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </section>
            <section id='all-inventory'>
                <h3>All inventory</h3>
                    <table>
                        <thead>
                            <tr>
                                <th></th>
                                <th>Product</th>
                                <th>Stock</th>
                                <th>Location</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in inventory %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a href="/inventory/{{ item.id }}/">{{ item.product }}</a></td>
                                    <td>{{ item.stock }}</td>
                                    <td>{{ item.location }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </section>
            <section id='all-locations'>
                <h3>All locations</h3>
                    <table>
                        <thead>
                            <tr>
                                <th></th>
                                <th>Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for location in locations %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a href="/locations/{{ location.id }}/">{{ location.name }}</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </section>
    {% endblock content %}
</div>
</body>
</html>

crud/templates/crud/inventory.html
{% extends 'crud/index.html' %}

{% block content %}
    <a href="{% url 'crud:add' 'inventory' %}" class="btn">Add Inventory</a>
    <h3>All inventory</h3>
    <table>
        <thead>
            <tr>
                <th></th>
                <th>Product</th>
                <th>Stock</th>
                <th>Location</th>
            </tr>
        </thead>
        <tbody>
            {% for item in inventory %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="/inventory/{{ item.id }}/">{{ item.product }}</a></td>
                    <td>{{ item.stock }}</td>
                    <td>{{ item.location }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

crud/templates/crud/locations.html
{% extends 'crud/index.html' %}

{% block content %}
    <a href="{% url 'crud:add' 'locations' %}" class="btn">Add Location</a>
    <h3>All locations</h3>
    <table>
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            {% for location in locations %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="/locations/{{ location.id }}/">{{ location.name }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

crud/templates/crud/products.html
{% extends 'crud/index.html' %}

{% block content %}
    <a href="{% url 'crud:add' 'products' %}" class="btn">Add Product</a>
    <h3>All products</h3>
    <table>
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="/products/{{ product.id }}/">{{ product.name }}</a></td>
                    <td>${{ product.price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}